### ISSUE TITLE
1.2.1 Doesn't seem to work on Thunderbird Daily (138.0a1)

### ISSUE THREAD

**Issue by WoofGrrrr** [Extended-Thunder/userChromeJS#2]
I'm sure you're not surprised, but I modified the manifest to allow a max version of 138.* and I get the following error:

```
19:29:41.375 1741562981374	addons.xpi	WARN	Exception running bootstrap method startup on userChromeJS@kamens.us: TypeError: ChromeUtils.import is not a function(jar:file:///C:/Users/XXX/AppData/Roaming/thunderbird/Profiles/2b2wch1z.default-nightly/extensions/userChromeJS@kamens.us.xpi!/experiments.js:3:40) JS Stack trace: @jar:file:///C:/Users/XXX/AppData/Roaming/thunderbird/Profiles/2b2wch1z.default-nightly/extensions/userChromeJS@experiments.js:3:40
asyncLoadModule/module.asyncLoaded<@ExtensionCommon.sys.mjs:1798:16 2
```

I'm a bit confused by this, as I thought you had changed it so it doesn't use ChromeUtils.import

>Non-functional change: convert "ChromeUtils.import" to "ChromeUtils.importESModule" for compatibility with upcoming Thunderbird releases.

**Comment by WoofGrrrr** [comment]
I'm sorry.  I am very confused.  This is strange.

I had initially downloaded using the "Download Now" button at the top of the Add-ons page, and I even verified that experiments.js still had ChromeUtils.import().

But just now I downloaded using button in the Version Information section, and it did install.  I verified that it is using ChromeUtils.importESModule()

And now I just tried using the button at the top of the page again, and this time I got the one using importESModule as well.  I must have really mucked the files up.  Sorry again.

**Comment by WoofGrrrr** [comment]
my mistake
